
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: sportweb_development

test:
  <<: *default
  database: sportweb_test


production:
  <<: *default
  database: sportweb_production
  username: sportweb
  password: <%= ENV['SPORTWEB_DATABASE_PASSWORD'] %>
